name: CodeSweep Full Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run CodeSweep with full publishing options
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@mattmurp-patch-1
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          service_url: https://cloud.appscan.com/
          publish_on_merge: false
          application_id: 622cb53e-12b2-4ce7-9581-8df10a9fb184
          scan_base_name: "CodeSweep"
          personal_scan: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOME: /github/workspace
