name: CodeSweep Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codesweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeSweep Action (test version)
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@mattmurp-patch-1
